version: '3'

services:

  db:
    image: "mysql:latest"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mercadolivro_db
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-data: