spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}/${MYSQL_DATABASE:mercadolivro_db}?createDatabaseIfNotExist=true&useSSL=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
