CREATE TABLE IF NOT EXISTS `book` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `price` DECIMAL(10,2) NOT NULL,
    `status` VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
)  ENGINE=INNODB;